# Site settings
title: Jasmine
header-img: 
email: xjasmine19@gmail.com
copyright_name: Jasmine
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "https://jasmine.github.io/"
twitter_username: jasmine
github_username:  jasmine
facebook_username: jasmine
email_username:  xjasmine19@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
